name: install-python-deps
description: Set up Python and install project dependencies.

inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.13'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        make install
        make install-test

