name: generate-quality-summary
description: Aggregate lint, test, coverage, and security summaries into a markdown report.

runs:
  using: "composite"
  steps:
    - name: Checkout artifacts folder
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/

    - name: Create comprehensive quality report
      shell: bash
      run: |
        echo "# TravelStyle AI Backend - Code Quality Report" > comprehensive_report.md
        echo "Generated on: $(date)" >> comprehensive_report.md
        echo "" >> comprehensive_report.md

        echo "## 🧪 Test Results" >> comprehensive_report.md
        if [ -d "artifacts/pytest-report" ]; then
          echo "✅ Tests completed - see pytest artifacts for details" >> comprehensive_report.md
        else
          echo "❌ Tests failed or not found" >> comprehensive_report.md
        fi
        echo "" >> comprehensive_report.md

        echo "## 📊 Coverage Report" >> comprehensive_report.md
        if [ -f "artifacts/coverage-summary/coverage_score.txt" ]; then
          cat artifacts/coverage-summary/coverage_score.txt >> comprehensive_report.md
        else
          echo "❌ Coverage report not available" >> comprehensive_report.md
        fi
        echo "" >> comprehensive_report.md

        echo "## 🔒 Security Scan" >> comprehensive_report.md
        if [ -f "artifacts/security-summary/security_score.txt" ]; then
          cat artifacts/security-summary/security_score.txt >> comprehensive_report.md
        else
          echo "❌ Security scan not available" >> comprehensive_report.md
        fi
        echo "" >> comprehensive_report.md

        echo "## 🔍 Code Quality (Pylint)" >> comprehensive_report.md
        if [ -f "artifacts/lint-summary/lint_score.txt" ]; then
          cat artifacts/lint-summary/lint_score.txt >> comprehensive_report.md
        else
          echo "❌ Lint report not available" >> comprehensive_report.md
        fi
        echo "" >> comprehensive_report.md

        echo "## 📁 Available Artifacts" >> comprehensive_report.md
        echo "- **pytest-report**: Test execution logs and cache" >> comprehensive_report.md
        echo "- **coverage-report**: HTML coverage report and JSON data" >> comprehensive_report.md
        echo "- **bandit-report**: Security scan results (JSON + HTML)" >> comprehensive_report.md
        echo "- **pylint-report**: Code quality reports (JSON + HTML)" >> comprehensive_report.md
        echo "- **quality-summary**: This comprehensive report" >> comprehensive_report.md
        echo "" >> comprehensive_report.md

        echo "## 🎯 Quick Links" >> comprehensive_report.md
        echo "- [View Coverage Report](../artifacts/coverage-report/htmlcov/index.html)" >> comprehensive_report.md
        echo "- [View Security Report](../artifacts/bandit-report/bandit_report.html)" >> comprehensive_report.md
        echo "- [View Pylint Report](../artifacts/pylint-report/pylint_report.html)" >> comprehensive_report.md

        echo "" >> comprehensive_report.md
        echo "---" >> comprehensive_report.md
        echo "*Report generated by TravelStyle AI Backend CI/CD Pipeline*" >> comprehensive_report.md

    - name: Upload comprehensive report
      uses: actions/upload-artifact@v4
      with:
        name: quality-summary
        path: comprehensive_report.md
