name: run-security-scan
description: Run Bandit security scan and upload reports.

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Run Bandit JSON report
      shell: bash
      run: |
        cd backend
        bandit -r app/ -f json -o bandit_report.json || true

    - name: Run Bandit HTML report
      shell: bash
      run: |
        cd backend
        bandit -r app/ -f html -o bandit_report.html || true

    - name: Upload bandit reports
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report
        path: backend/bandit_report.json,backend/bandit_report.html

    - name: Extract security issue count
      shell: bash
      run: |
        python backend/extract_security_score.py bandit_report.json > security_score.txt || echo "0" > security_score.txt
        cat security_score.txt

    - name: Upload security summary
      uses: actions/upload-artifact@v4
      with:
        name: security-summary
        path: backend/security_score.txt

